<?php

use Drupal\block_content\BlockContentInterface;

/**
 * Implements hook_preprocess_HOOK().
 */
function inno_practice_preprocess_block(&$variables) {
  // Add a class depending on the type of block content.
  $content = $variables['elements']['content'];
  if (isset($content['#block_content']) && $content['#block_content'] instanceof BlockContentInterface) {
    $bundle = $content['#block_content']->bundle();
    $variables['attributes']['class'][] = 'block-block-content-' . strtr($bundle, '_', '-');

    if (isset($content['#block_content']->type) == 'notice') {
      $variables['#attached']['library'][] = 'inno_practice/notice_block';
    }
  }

}

/**
 * Implements hook_preprocess_page().
 */
function inno_practice_preprocess_page(&$variables) {
  if (\Drupal::service('path.matcher')->isFrontPage()) {

    $config = \Drupal::config('message.adminsettings');
    $msg = $config->get('welcome_message');

    $variables['#attached']['library'][] = 'inno_practice/message_alert';
    $variables['#attached']['drupalSettings']['message_alert']['message'] = $msg;
  }
}
